schema_version = 3

[project]
uuid = "1d1c03f0-3746-4ed0-ad24-ab5edc5697d5"
name = "covledger"

[ledgers.taskledger.mounts.data]
storage = "external"
root = "../ledger"

[ledgers.taskledger.mounts.runtime]
storage = "user-data"

[ledgers.taskledger.mounts.logs]
storage = "user-data"

[ledgers.taskledger.mounts.indexes]
storage = "cache"

[ledgers.releaseledger.mounts.data]
storage = "project"

[ledgers.releaseledger.mounts.indexes]
storage = "cache"

[ledgers.covledger.mounts.cache]
storage = "cache"
