import hashlib
from pathlib import Path

import pytest

from covledger.source import classify_source, discover_python_files, extract_functions, read_verified_source
from covledger.storage import StaleAnalysisError


def test_generated_sources_are_excluded_by_default(tmp_path: Path) -> None:
    generated = tmp_path / "context_covledger.unpack.py"
    generated.write_text("# Generated by codecrate\ndef unpack():\n    return None\n", encoding="utf-8")
    ordinary = tmp_path / "app.py"
    ordinary.write_text("def run():\n    return 1\n", encoding="utf-8")

    assert classify_source(generated, root=tmp_path).generated is True
    assert discover_python_files(tmp_path) == [ordinary]
    assert discover_python_files(tmp_path, include_generated=True) == [ordinary, generated]


def test_extracts_python_facts(tmp_path: Path) -> None:
    path = tmp_path / "sample.py"
    path.write_text(
        "def risky(items=[]):\n"
        "    try:\n"
        "        if items:\n"
        "            return eval(items[0])\n"
        "    except Exception:\n"
        "        return None\n"
        "    return 0\n",
        encoding="utf-8",
    )
    [function] = extract_functions(path, root=tmp_path)
    assert function.qualname == "risky"
    assert function.mutable_default is True
    assert function.broad_except is True
    assert function.exception_handlers[0]["contains_return"] is True
    assert function.exception_handlers[0]["contains_raise"] is False
    assert function.eval_exec_calls == ("eval",)
    assert "mutable-default" in function.exact_findings
    assert "broad-except" in function.exact_findings


def test_read_verified_source_uses_current_checkout_and_hash(tmp_path: Path) -> None:
    source = tmp_path / "pkg" / "module.py"
    source.parent.mkdir()
    source.write_text("def value(): return 1\n", encoding="utf-8")
    expected = hashlib.sha256(source.read_bytes()).hexdigest()

    assert read_verified_source(tmp_path, "pkg/module.py", expected) == "def value(): return 1\n"

    source.write_text("def value(): return 2\n", encoding="utf-8")
    with pytest.raises(StaleAnalysisError, match="pkg/module.py"):
        read_verified_source(tmp_path, "pkg/module.py", expected)


def test_read_verified_source_rejects_outside_project_paths(tmp_path: Path) -> None:
    with pytest.raises(StaleAnalysisError, match="outside.py"):
        read_verified_source(tmp_path, "../outside.py", "0" * 64)
